gosip/gosip/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'gosip.views.login_view'),
    url(r'^login/$', 'gosip.views.login_view', name='login'),
    url(r'^logout/$', 'gosip.views.logout_view', name='logout'),
    url(r'^signup/$', 'gosip.views.signup_view', name='signup'),
    url(r'^about/$', 'gosip.views.about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^history/', include('history.urls')),
    url(r'^identity/', include('identity.urls')),
    url(r'^map/', include('map.urls', namespace='map')),
    url(r'^social-profile/', include('social_profile.urls', namespace='social_profile')),
    #(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'history.views.not_found'

gosip/map/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'map.views.navigation'),
    url(r'^(?P<next>\d+)$', 'map.views.navigation', name='navigation'),
    url(r'^place/(?P<previous_edge>\d+)/(?P<place_pk>\d+)$', 'map.views.place', name='place'),           
)

gosip/gosip/forms.py
# coding: utf-8
'''
Created on 08/07/2014

@author: Welington
'''
from django.contrib.auth.forms import UserCreationForm


class GosipUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(GosipUserCreationForm, self).__init__(*args, **kwargs)

        # if you want to do it to all of them
        for field in self.fields.values():
            print field
            field.error_messages = {'required':'O campo {fieldname} é obrigatório'.format(
                fieldname=field.label)}

gosip/history/forms.py
from django import forms

from identity.models import Respondent


class StepForm(forms.Form):
    step_page   = forms.CharField(widget=forms.HiddenInput(), max_length=100, min_length=1)
    step_answer = forms.CharField(widget=forms.HiddenInput(), max_length=100, min_length=1)
    
class DeductForm(forms.Form):
    value = forms.DecimalField(max_digits=9, decimal_places=2, widget=forms.HiddenInput())
    context = forms.CharField(widget=forms.HiddenInput(), max_length=100, min_length=1)
    
class ServiceForm(forms.Form):
    service  = forms.CharField(widget=forms.HiddenInput(), max_length=100, min_length=1)
    exposure = forms.CharField(widget=forms.HiddenInput(), max_length=100, min_length=1)
    
class CallForm(forms.Form):
    phone_number = forms.CharField( max_length=20, min_length=1)
    
class TwistterForm(forms.Form):
    text = forms.CharField(max_length=100, min_length=1)
    
class FakebookForm(forms.Form):
    receiver = forms.ChoiceField(widget=forms.Select(), required=True)
    content  = forms.CharField(max_length=400, min_length=1, required=True)
    
    def __init__(self, respondent, *args, **kwars):
        super(FakebookForm, self).__init__(*args, **kwars)
        self.fields['receiver'] = forms.ChoiceField(choices=[ (o.pk, str(o)) for o in respondent.friends.all()]) 

gosip/gosip/views.py
# encoding: utf-8
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext

from gosip.constants import retrieve_errors
from identity.models import Respondent


def login_view(request):
    context = RequestContext(request)
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
    
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/history')
            else:
                messages.error(request, 'Sua conta está inativa!')
        else:
            messages.error(request, 'Login e/ou Senha Inválidos!')
    else:
        user = request.user
        
        if user.is_authenticated():
            #messages.info(request, 'Você já estava autenticado')
            return HttpResponseRedirect('/history')
    
    signup_form = UserCreationForm()
    
    return render_to_response('gosip/login.html', locals(), context)

def signup_view(request):
    context = RequestContext(request)
    
    if request.method == 'POST':
        
        signup_form = UserCreationForm(request.POST)
        
        if signup_form.is_valid():
            user = signup_form.save()
            
            respondent = Respondent()
            respondent.user = user
            respondent.show_score = (Respondent.objects.count() % 2 == 0)
            
            respondent.save()
            
            messages.success(request, 'Cadastro realizado com sucesso!')
            
            new_user = authenticate(username=request.POST['username'],
                                    password=request.POST['password1'])
            login(request, new_user)
            
            return HttpResponseRedirect(reverse('history.views.step'))
        else:
            retrieve_errors(request, signup_form)
    else:
        signup_form = UserCreationForm()
        
    return render_to_response('gosip/login.html', locals(), context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/login')

def about(request):
    return render(request, 'gosip/about.html')

gosip/gosip/templates/gosip/about.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        {% extends "gosip:gosip/base.html" %}
        {% load static %}
        
        {% block title %}Sobre{% endblock %}
        {% block about %}active{% endblock %}
        
        {% block content %}
        <h4>Sobre o Go!SIP</h4>
        <hr>
        
        <p class="text-justify">A ideia do Go!SIP surgiu dentro do programa de pós graduação do <a href="http://www.cin.ufpe.br/" target="_blank">Centro de Informática</a>, da <a href="http://www.ufpe.br/ufpenova/" target="_blank">Universidade Federal de Pernambuco</a>.</p>
        
        <p class="text-justify">O nome <strong>Go!SIP</strong>, é uma composição de "<em>Go</em>" (do verbo ir, avançar, em inglês) - uma alusão ao estímulo à exposição segura de dados, e de  
        <em>SIP</em>, uma sigla para <em>Smart Identification Privacy</em> (do inglês Privacidade de Identificação Inteligente). Finalmente, o nome Go!SIP é um trocadilho oportuno da palavra <em>gossip</em>, que significa fofocar, bisbilhotar, mexericar.</p>
        
        <p class="text-justify">Imaginando o cenário de exposição de informação de dados pessoais no qual estamos imersos atualmente e vislumbrando a importância que a questão privacidade vai assumir nos próximos anos, a proposta do meu projeto de mestrado é discutir como 
        os problemas decorrentes da utilização, quase que constante, de dados pessoais podem ser tratados, não do ponto de vista "dados" ou do que pode ser feito com eles e sim do ponto de vista "usuário", propondo uma soluçao que tenha em vista como cidadãos comuns podem usufruir de serviços que utilizem suas informações
        pessoais de forma transparente, de modo que cada pessoa tenha total consciência dos riscos e benefícios ao optar por utilizar algum serviço (como redes sociais, localização, pagamento, compras, etc.), a fim de que tome decisões bem fundamentadas. Tudo isso a ser aplicado futuramente ao contexto de Cidades Inteligentes.</p>
        
        <p class="text-justify">Em resumo, o propósito final é dar ao indivíduo o controle sobre seus dados e tentar atribuir-lhe o direito de decidir o que fazer com eles.</p>
        
        <p class="text-justify">Este é só um passo inicial, de uma longa caminhada que envolve, desde conscientização e contextualização de pessoas sobre seus dados e como tirar proveito deles, a descoberta de novos planos de negócio na utilização de dados pessoais e um conjunto de regulamentações adequadas.</p>
                
        <p class="text-right" ><a class="btn btn-default" href="/" role="button">Voltar</a></p>

        {% endblock content %}

        {% block script %}
        {% endblock script %}
    </body>
</html>

gosip/gosip/templates/gosip/base.html
<!DOCTYPE html>

{% load static %}
    
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GO!SIP | {% block title %}{% endblock %}</title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,900' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-editable.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-growl.css' %}" rel="stylesheet">
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/say-cheese.css' %}" rel="stylesheet">    
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <link href="{% static 'css/slider.css' %}" rel="stylesheet">
    
    
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">GO!SIP</a>
          </div>
          <div class="collapse navbar-collapse">
            {% block menu %}
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">	            
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">{% if respondent.name != None %}
	                Olá, <strong id="user_first_name">{{ respondent.name }}</strong>
	                {% else  %}
	                Olá, <strong id="user_first_name">Turista</strong>
	                {% endif  %} <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="{% url 'history.views.profile' %}">Meus Dados</a></li>
						<li class="divider"></li>
						<li><a href="/logout">Sair</a></li>
					</ul>
				</li>
            </ul>
            {% else %}
			<ul class="nav navbar-nav">
			    <li class="{% block home %}{% endblock %}"><a href="/">Home</a></li>
			    <!-- <li class="{% block about %}{% endblock %}"><a href="/about">Sobre</a></li>  -->
			</ul>	  
			{% endif %}
			
			{% endblock %}         
          </div><!--/.nav-collapse -->
        </div>
      </div>
		
      <div class="container">
      		<!--  {{ curr_page }} --> 
		    {% block content %}
        	{% endblock content %}
      </div>

    <div id="footer">
      <div class="container">
	      <div class="row">
		      <div class="col-md-12 col-sm-12">
		        <p class="text-muted text-center">Desenvolvido por <a href="http://welingtonms.wordpress.com/"  target="_blank">Welington Silva</a> e <a href="http://gustahrodrigues.wordpress.com/"  target="_blank">Gustavo Henrique</a>. 2014. CIn-UFPE | Bug? <a>wms4@cin.ufpe.br</a></p>
		      </div>
	      </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/bootstrap-editable.min.js' %}"></script>
	<script src="{% static 'js/jquery.bootstrap-growl.min.js' %}"></script>
	<script src="{% static 'js/scrollToggle.js' %}"></script>
	<script src="{% static 'js/jquery.mask.min.js' %}"></script>
	<script src="{% static 'js/say-cheese.js' %}"></script>
	<script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
	<script src="{% static 'js/bootstrap-slider.js' %}"></script>
  	
    
    <script type="text/javascript">
    	$.fn.editable.defaults.mode = 'popup';  

    	{% if messages %}
		{% for message in messages %}
			showNotification('{{ message.tags }}', '{{message}}')
		{% endfor %}
		{% endif %}
		
		function showNotification(tags, message) {
			$.bootstrapGrowl(message, { 
				type: tags,
				align: 'center',
				width: 'auto',
	            allow_dismiss: false,
	            delay: 16000
			});
		}
	
		function setValues(step_answer) {
			$("#id_step_answer").val(step_answer);
			
			$("#step_form").submit();
		}
		
		$(function () {
		    $('.btn-radio').click(function(e) {
		        $('.btn-radio').not(this).removeClass('active')
		    		.siblings('input').prop('checked',false)
		            .siblings('.img-radio').css('opacity','0.5');
		    	$(this).addClass('active')
		            .siblings('input').prop('checked',true)
		    		.siblings('.img-radio').css('opacity','1');
		    });
		});

		$(document).ready(function(){
			$('.date').mask('99/99/9999');
			$('.number').mask('0000000000');
			
			 $('#modal-gosip-app-fakebook').on('show.bs.modal', function (e) {
	        	asyncSubmission('#fakebook_form', "{% url 'history.views.mark_read' %}", function() {console.log('ok')}, function() {console.log('N ok')});          		
         	});
			 
			 $('#modal-gosip-app-fakebook').on('hidden.bs.modal', function (e) {
          		reload();
         	});
		});

		function initializeCamera() {
	        var sayCheese = new SayCheese('#say-cheese-container', { audio: false });

	        sayCheese.on('start', function() {
	          $('#take-snapshot').on('click', function(evt) {
	            sayCheese.takeSnapshot();
	            if ($("#id_value").val() > 0) {
	        		var new_value = $("#id_value").val() - 4;
	       			$("#total-order").text(new_value);
	       			$("#id_value").val(new_value);
	        	}
	            $("#id_context").val('8c;com foto');
	          });
	        });

	        sayCheese.on('error', function(error) {
	          var msg = '';

	          if (error === 'NOT_SUPPORTED') {
	        	  msg = "<strong>:(</strong> seu browser não suporta vídeo!";
	          } else if (error === 'AUDIO_NOT_SUPPORTED') {
	        	  msg = "<strong>:(</strong> seu browser não suporta áudio!!";
	          } else {
	        	  msg = "<strong>:(</strong> você precisar clicar em 'Permitir' (ou 'Allow') para conseguir fazer o checkin!";
	          }

	          showNotification('danger', msg);
	          $('#modal-take-photo').modal('hide');
	        });

	        sayCheese.on('snapshot', function(snapshot) {
	          var img = document.createElement('img');

	          $(img).addClass( "img-responsive" );
	          $(img).addClass( "col-sm-3" );
	          $(img).addClass( "col-md-3" ); 
	          
	          $(img).on('load', function() {
	            $('#say-cheese-snapshots').prepend(img);
	          });
	          img.src = snapshot.toDataURL('image/png');
	        });

	        sayCheese.start();
	        
	        $('#modal-take-photo').on('hidden.bs.modal', function (e) {
          		sayCheese.stop();
         	});
	        	        
	      };

	      function convertToColor(id, value) {
		
// 	    	  var r = Math.floor((255*value)/100);
// 	    	  var g = Math.floor((255*(100-value))/100); 
// 	    	  var b=0;
//  	   	  console.log(id  +' ' +  "rgb(" + r + "," + g + "," + b + ");");
// 	    	  $(id).css('background-color', "rgb(" + r + "," + g + "," + b + ");");
	    	  $(id).css('background-color', "hsl(" + (100 - value) + ", 100%, 50%);");
	      }
	      	      
	      function reload() {
	    		location.reload();  
	      }
	      
	      function asyncSubmission(id, url, onsuccess, onerror) {
    		var data = $(id).serialize(); // serializes the form's elements

    	    $.ajax({
    	       type: "POST",
    	       url: url,
    	       data: data,
    	       success: onsuccess,
    	       error: onerror
    	     });

    	    return false; // avoid to execute the actual submit of the form.
    	}
	</script>

    {% block scripts %}
    {% endblock scripts%}
    
    <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
	  ga('create', 'UA-52728611-1', 'auto');
	  ga('send', 'pageview');
	
	</script>

    {% block popups %}
    {% endblock %}
  </body>
</html>

gosip/gosip/templates/gosip/login.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        {% extends "gosip:gosip/base.html" %}
        {% load staticfiles %}
        {% load widget_tweaks %}
        
        {% block title %}Principal{% endblock %}
        {% block home %}active{% endblock %}
        
        {% block content %}

        <div style="padding: 10%">
           <div class="row" style="margin-bottom: 3%">
               <div class="col-sm-8 col-sm-offset-2 text-justify">
                   <!-- <p>Antes de começar, <a alt="Sobre o Go!SIP" href="/about">saiba um pouco mais</a> sobre o Go!SIP e qual a importância da sua participação no projeto.</p>  -->
                   <p>Primeiramente, obrigado pela sua participação na avaliação da proposta do meu projeto de mestrado.</p>
                   <p>Para iniciar, basta criar um <em>login</em> e escolher sua senha. Simples assim...</p>
                   
               </div>
           </div>
            <div class="row">
                <div class="col-md-6 col-sm-6">
                
                    <form class="" role="form" id="login_form" method="post" action="{% url 'gosip.views.login_view' %}">
                        {% csrf_token %}
                        <div class="row">
                            <label for="inputEmail3" class="col-sm-2 col-sm-offset-2 control-label">Login</label>
                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="username" placeholder="digite seu login" name="username" autofocus="autofocus">
                            </div>
                        </div>
                        <div class="row hold-top">
                            <label for="inputPassword3" class="col-sm-2 col-sm-offset-2 control-label">Senha</label>
                            <div class="col-sm-6">
                                <input type="password" class="form-control" id="password" placeholder="digite sua senha" name="password">
                            </div>
                        </div>
                        <div class="row hold-top">
                            <label for="inputPassword3" class="col-sm-4 col-sm-offset-2 control-label invisible">Confirmação</label>
                            <div class="col-sm-6">
                                <input id="id_password2" class="form-control invisible" name="password2" type="password" placeholder="repita sua senha"/>
                            </div>
                        </div>
                        <div class="row hold-top">
                            <div class="col-md-6 col-sm-6 col-sm-offset-4 ">
	                            <div class="btn-group btn-group-justified">
								  	<div class="btn-group">
						  				<button type="submit" class="btn btn-primary">Quero Entrar</button>
						  			</div>
						  		</div>
                            </div>
                        </div>
                    </form>
                    
                </div>
                
                <div class="col-md-6 col-sm-6">
                    <form class="form-horizontal" role="form" id="signup_form" method="post" action="{% url 'gosip.views.signup_view' %}">
                        {% csrf_token %}
                        <div class="row">
                            <label for="inputEmail3" class="col-sm-4 col-sm-offset-2 control-label">Login</label>
                            <div class="col-sm-6">
                                <input id="id_username" class="form-control" maxlength="30" name="username" type="text" placeholder="escolha seu usuário"/>
                            </div>
                        </div>
                        <div class="row hold-top">
                            <label for="inputPassword3" class="col-sm-4 col-sm-offset-2 control-label">Senha</label>
                            <div class="col-sm-6">
                                <input id="id_password1" class="form-control" name="password1" type="password" placeholder="digite sua senha"/>
                            </div>
                        </div>
                        <div class="row hold-top">
                            <label for="inputPassword3" class="col-sm-4 col-sm-offset-2 control-label">Confirmação</label>
                            <div class="col-sm-6">
                                <input id="id_password2" class="form-control" name="password2" type="password" placeholder="repita sua senha"/>
                            </div>
                        </div>
                        
                        <div class="row hold-top">
                            <div class="col-md-6 col-sm-6 col-sm-offset-6 ">
	                            <div class="btn-group btn-group-justified">
								  	<div class="btn-group">
						  				<button type="submit" class="btn btn-default">Quero me Cadastrar</button>
						  			</div>
						  		</div>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
	        
        {% endblock content %}

    </body>
</html>